/**
 * electron-builder `afterPack` hook.
 *
 * Runs once per per-arch packed .app (before signing, before the universal
 * merge, before dmg generation). We use it to inject the Next.js standalone
 * server bundle into Contents/Resources/app/. Doing this here — rather than
 * rsyncing into the dir output afterwards — means:
 *   - the standalone gets signed alongside everything else,
 *   - the universal-merge step sees the same content in both arch trees,
 *   - the .dmg generated by electron-builder contains a complete .app.
 *
 * electron-builder's own extraResources mechanism strips `node_modules/`
 * from copies no matter the filter expression, which is why we do this
 * with rsync instead.
 */

const path = require("node:path");
const { execFileSync } = require("node:child_process");
const { existsSync } = require("node:fs");

module.exports = async function afterPack(context) {
  const repoRoot = path.join(__dirname, "..");
  const productFilename =
    context.packager.appInfo.productFilename || "WeChat Explorer";
  const appPath = path.join(context.appOutDir, `${productFilename}.app`);
  const appResources = path.join(appPath, "Contents", "Resources", "app");
  const standaloneTarget = path.join(appResources, ".next", "standalone");

  const standaloneSrc = path.join(repoRoot, ".next", "standalone");
  const staticSrc = path.join(repoRoot, ".next", "static");
  const publicSrc = path.join(repoRoot, "public");

  if (!existsSync(standaloneSrc)) {
    throw new Error(
      `afterPack: missing ${standaloneSrc} — did \`next build\` (output: 'standalone') run first?`,
    );
  }

  execFileSync("mkdir", ["-p", standaloneTarget]);
  // `rsync -a` preserves perms/times; trailing slashes are deliberate so
  // we copy contents-of-dir into target, not the dir itself.
  execFileSync("rsync", ["-a", "--delete", `${standaloneSrc}/`, `${standaloneTarget}/`]);
  execFileSync("rsync", [
    "-a",
    "--delete",
    `${staticSrc}/`,
    `${path.join(standaloneTarget, ".next", "static")}/`,
  ]);
  execFileSync("rsync", [
    "-a",
    "--delete",
    `${publicSrc}/`,
    `${path.join(standaloneTarget, "public")}/`,
  ]);

  // Strip sharp + its prebuilt arch-specific .node binaries. Next.js's
  // standalone tracer pulls sharp in for the (unused-by-us) image
  // optimizer, and the arch-specific `@img/sharp-darwin-{arm64,x64}`
  // .node files trip @electron/universal's merge — same file in both
  // per-arch trees, but only one arch can actually load it. We don't
  // use next/image anywhere, so deleting the whole sharp tree is safe.
  for (const dir of ["sharp", "@img"]) {
    execFileSync("rm", [
      "-rf",
      path.join(standaloneTarget, "node_modules", dir),
    ]);
  }

  // Belt-and-suspenders against the Next.js tracer's "trace the world"
  // behaviour with dynamic spawn(). next.config.ts's
  // outputFileTracingExcludes already filters these, but a previous
  // `release/` directory still on disk during the next build can sneak
  // into the bundle. Strip them post-rsync just in case.
  for (const stale of [
    "release",
    "build",
    "electron",
    "scripts",
    "tests",
    ".github",
    "AGENTS.md",
    "CLAUDE.md",
    "README.md",
    "INSTALL.md",
    "TROUBLESHOOTING.md",
    "task_plan.md",
    "findings.md",
    "progress.md",
    "bun.lock",
    "package-lock.json",
  ]) {
    execFileSync("rm", ["-rf", path.join(standaloneTarget, stale)]);
  }

  // Strip extended attributes that would otherwise trip codesign with
  // "resource fork, Finder information, or similar detritus not allowed".
  // `xattr -cr` clears all xattrs recursively; the bundle has none we want
  // to keep at this stage.
  execFileSync("xattr", ["-cr", appPath]);

  console.log(`  [afterPack] standalone copied + xattrs cleared in ${appPath}`);
};
